site_name: "EasyBuild tutorial"
google_analytics:
    - UA-168742780-1
    - auto
theme:
  name: material
  logo: img/easybuild_logo.png
  features:
      - instant
repo_name: EasyBuild @ GitHub
repo_url: https://github.com/easybuilders
edit_uri: easybuild-tutorial/edit/master/docs
nav:
  - "Home": index.md
  - Practical information: practical_information/README.md
  - Introduction: introduction/README.md
  - Installation: installation/README.md
  - Configuration: configuration/README.md
  - Basic usage: basic_usage/README.md
  - Troubleshooting: troubleshooting/README.md
  - Hierarchical module naming schemes: hmns/README.md
  - Adding support for additional software: adding_support_software/README.md
  - EasyBuild at Jülich Supercomputing Centre: jsc/README.md
  - EasyBuild at Compute Canada: computecanada/README.md
  - The EasyBuild Community: community/README.md
  - Contributing to EasyBuild: contributing/README.md
  - Comparison with other tools: comparison_other_tools/README.md
  - Getting help: getting_help/README.md
plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true
extra:
  # add links in bottom right
  social:
    - type: github
      icon: octicons/logo-github
      link: https://github.com/easybuilders
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/easy_build
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/easybuilders
    - icon: fontawesome/solid/book
      link: https://easybuild.readthedocs.io
