site_name: "EasyBuild tutorial"
google_analytics:
    - UA-168742780-1
    - auto
theme:
  name: material
  logo: img/easybuild_logo.png
  features:
      - instant
repo_name: EasyBuild @ GitHub
repo_url: https://github.com/easybuilders
edit_uri: easybuild-tutorial/edit/master/docs
nav:
  - Home: index.md
  - "ISC-20 (June '20)":
      - Start page: 2020-06-isc20/index.md
      - Practical information: 2020-06-isc20/practical_information.md
      - Introduction: 2020-06-isc20/introduction.md
      - Installation: 2020-06-isc20/installation.md
      - Configuration: 2020-06-isc20/configuration.md
      - Basic usage: 2020-06-isc20/basic_usage.md
      - Troubleshooting: 2020-06-isc20/troubleshooting.md
      - Hierarchical module naming schemes: 2020-06-isc20/hmns.md
      - Adding support for additional software: 2020-06-isc20/adding_support_software.md
      - EasyBuild at Jülich Supercomputing Centre: 2020-06-isc20/jsc.md
      - EasyBuild at Compute Canada: 2020-06-isc20/computecanada.md
      - The EasyBuild community: 2020-06-isc20/community.md
      - Contributing to EasyBuild: 2020-06-isc20/contributing.md
      - Comparison with other tools: 2020-06-isc20/comparison_other_tools.md
      - Getting help: 2020-06-isc20/getting_help.md
  - "LUST (spring '21)":
      - Overview: 2021-lust/index.md
      - Introduction to EasyBuild:
          - What is EasyBuild?: 2021-lust/what_is_easybuild.md
          - Terminology: 2021-lust/terminology.md
          - Installation: 2021-lust/installation.md
          - Configuration: 2021-lust/configuration.md
          - Basic usage: 2021-lust/basic_usage.md
      - Using EasyBuild:
          - Creating easyconfig files: 2021-lust/creating_easyconfig_files.md
      - Advanced topics: 2021-lust/part3_advanced.md
      - EasyBuild on Cray systems: 2021-lust/part4_cray.md
plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
  # redirects to avoid broken URLs in original version of the tutorial (June 2020)
  - redirects:
      redirect_maps:
          practical_information.md: 2020-06-isc20/practical_information.md
          introduction.md: 2020-06-isc20/introduction.md
          installation.md: 2020-06-isc20/installation.md
          configuration.md: 2020-06-isc20/configuration.md
          basic_usage.md: 2020-06-isc20/basic_usage.md
          troubleshooting.md: 2020-06-isc20/troubleshooting.md
          hmns.md: 2020-06-isc20/hmns.md
          adding_support_software.md: 2020-06-isc20/adding_support_software.md
          jsc.md: 2020-06-isc20/jsc.md
          computecanada.md: 2020-06-isc20/computecanada.md
          community.md: 2020-06-isc20/community.md
          contributing.md: 2020-06-isc20/contributing.md
          comparison_other_tools.md: 2020-06-isc20/comparison_other_tools.md
          getting_help.md: 2020-06-isc20/getting_help.md

markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true
extra:
  # add links in bottom right
  social:
      #- type: github
      #icon: octicons/logo-github
      #link: https://github.com/easybuilders
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/easy_build
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/easybuilders
    - icon: fontawesome/solid/book
      link: https://easybuild.readthedocs.io
