site_name: "EasyBuild tutorial"
google_analytics:
    - UA-168742780-1
    - auto
theme:
  name: material
  logo: img/easybuild_logo.png
  features:
      - instant
repo_name: EasyBuild @ GitHub
repo_url: https://github.com/easybuilders
edit_uri: easybuild-tutorial/edit/master/docs
nav:
  - Home: index.md
  - "ISC-20 (June '20)":
      - Start page: 2020-06-isc20/README.md
      - Practical information: 2020-06-isc20/practical_information/README.md
      - Introduction: 2020-06-isc20/introduction/README.md
      - Installation: 2020-06-isc20/installation/README.md
      - Configuration: 2020-06-isc20/configuration/README.md
      - Basic usage: 2020-06-isc20/basic_usage/README.md
      - Troubleshooting: 2020-06-isc20/troubleshooting/README.md
      - Hierarchical module naming schemes: 2020-06-isc20/hmns/README.md
      - Adding support for additional software: 2020-06-isc20/adding_support_software/README.md
      - EasyBuild at Jülich Supercomputing Centre: 2020-06-isc20/jsc/README.md
      - EasyBuild at Compute Canada: 2020-06-isc20/computecanada/README.md
      - The EasyBuild community: 2020-06-isc20/community/README.md
      - Contributing to EasyBuild: 2020-06-isc20/contributing/README.md
      - Comparison with other tools: 2020-06-isc20/comparison_other_tools/README.md
      - Getting help: 2020-06-isc20/getting_help/README.md
  - "LUST (spring '21)":
      - Start page: 2021-lust/README.md
plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
  # redirects to avoid broken URLs in original version of the tutorial (June 2020)
  - redirects:
      redirect_maps:
          practical_information/README.md: 2020-06-isc20/practical_information/README.md
          introduction/README.md: 2020-06-isc20/introduction/README.md
          installation/README.md: 2020-06-isc20/installation/README.md
          configuration/README.md: 2020-06-isc20/configuration/README.md
          basic_usage/README.md: 2020-06-isc20/basic_usage/README.md
          troubleshooting/README.md: 2020-06-isc20/troubleshooting/README.md
          hmns/README.md: 2020-06-isc20/hmns/README.md
          adding_support_software/README.md: 2020-06-isc20/adding_support_software/README.md
          jsc/README.md: 2020-06-isc20/jsc/README.md
          computecanada/README.md: 2020-06-isc20/computecanada/README.md
          community/README.md: 2020-06-isc20/community/README.md
          contributing/README.md: 2020-06-isc20/contributing/README.md
          comparison_other_tools/README.md: 2020-06-isc20/comparison_other_tools/README.md
          getting_help/README.md: 2020-06-isc20/getting_help/README.md

markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true
extra:
  # add links in bottom right
  social:
      #- type: github
      #icon: octicons/logo-github
      #link: https://github.com/easybuilders
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/easy_build
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/easybuilders
    - icon: fontawesome/solid/book
      link: https://easybuild.readthedocs.io
