site_name: "EasyBuild tutorial"
google_analytics:
    - UA-168742780-1
    - auto
theme:
  name: material
  logo: img/easybuild_logo.png
  features:
      - instant
      - tabs
repo_name: EasyBuild @ GitHub
repo_url: https://github.com/easybuilders
edit_uri: easybuild-tutorial/edit/master/docs
nav:
  - "": index.md
  - 0. Practical information: 00_practical_information/README.md
  - 1. Introduction: 01_introduction/README.md
  - 2. Installation: 02_installation/README.md
  - 3. Configuration: 03_configuration/README.md
  - 4. Basic usage: 04_basic_usage/README.md
  - 5. Troubleshooting: 05_troubleshooting/README.md
  - 6. Beyond the basics: 06_beyond_the_basics/README.md
  - 7. Hierarchical module naming schemes: 07_hmns/README.md
  - 8. Adding support for additional software: 08_adding_support_software/README.md
  - 9. EasyBuild at Jülich Supercomputing Centre: 09_jsc/README.md
  - 10. EasyBuild at Compute Canada: 10_computecanada/README.md
  - 11. The EasyBuild Community: 11_community/README.md
  - 12. Contributing to EasyBuild: 12_contributing/README.md
  - 13. Comparison with other tools: 13_comparison_other_tools/README.md
  - 14. Getting help: 14_getting_help/README.md
plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true
extra:
  # add links in bottom right
  social:
    - type: github
      icon: octicons/logo-github
      link: https://github.com/easybuilders
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/easy_build
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/easybuilders
    - icon: fontawesome/solid/book
      link: https://easybuild.readthedocs.io
